version: '3'
services:
  toxin-app:
    build:
      context: .
      dockerfile: app/configs/docker/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/toxin-app
    environment:
      - NODE_ENV=production

  toxin-app-dev:
    build:
      context: .
      dockerfile: app/configs/docker/Dockerfile.dev
    ports:
      - '8000:8000'
    volumes:
      - .:/toxin-app
    environment:
      - NODE_ENV=development
